version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db_mysql
    env_file:
      - .env
    environment:
      - GIN_MODE=${GIN_MODE}
      - DB_TYPE=${DB_TYPE}
      - DB_DSN=${DB_DSN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}

  db_mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_mysql_data:/var/lib/mysql

#  db_postgres:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DATABASE}
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_postgres_data:/var/lib/postgresql/data


volumes:
  db_mysql_data:
#  db_postgres_data: